site_name: Tarmo Johannes's site 
site_url: https://tarmoj.github.io

markdown_extensions:
  - attr_list
theme:
  name: terminal
  palette: dark
  features:
    - footer.prev_next
#    - navigation.side.hide
#    - navigation.side.toc.hide
    - navigation.top.hide
    - navigation.top.cursor_animation.hide
    - navigation.top.search_button.hide
    - revision.date
    - revision.history
    
nav:
  - Home: index.md
  - DUOS: duos.md
  - Software: software.md
  - Koosm√§nguklubi: klubi.md

# pip install mkdocs-exclude  
plugins:
  - exclude:
      glob:
        - "*.backup"
        - "*.bak"
        - "*.tmp"

